Enet4/dicom-rs

- core/src/header.rs
@ibaryshnikov I suppose this is what you had in mind? I am not opposed to the existence of this method, and at this stage, identifying useful methods and other pieces that feel missing from the API is much more important than rock-solid stability.
> Add DataElement.into_value

- encoding/src/text.rs
- parser/src/stateful/decode.rs
Fixed an error in parsing character encoding and added support for Chinese characters.
Resolves #51.
> fix parse Specific Character Set error

- dcmdump/src/main.rs
- Print transfer syntax name alongside UID when known
- Show Implementation Class UID instead of Transfer Syntax UID in its respective field
- Explicitly print errors in human readable form
> [dcmdump] fix and improve file meta table output

- core/src/value/primitive.rs
These methods were still missing.
- `PrimitiveValue::to_multi_date`
- `PrimitiveValue::to_multi_time`
- `PrimitiveValue::to_multi_datetime`
> [core] Add PrimitiveValue::to_multi_{date,time,datetime}

- core/src/value/primitive.rs
I detected some cases where `PrimitiveValue::calculate_byte_len` would not give a valid output,
which resulted in an incorrect number of bytes shown in dcmdump.
- In textual multi-values, it should properly account for the backslash separator character,
and only assume trailing padding in the last value, hence always returning an even number
- Assume also that all 8 bytes of a date are fully written (see also #55)
> Fix incorrect outputs of calculate_byte_len

- core/src/header.rs
- core/src/value/mod.rs
> Extend date/time value getters to Value and DataElement

- core/src/header.rs
- core/src/value/mod.rs
- core/src/value/primitive.rs
Implementation of a getter method and tests to clean a string or multiple strings from unwanted whitespaces.
> Implementation of getter method to clean strings

- object/src/lib.rs
- object/src/mem.rs
- add example to root object docs
- also improve documentation of `read_dataset` and `write_dataset`
> Add write_dataset_with_ts to in-mem object

- dcmdump/src/main.rs
- trim ending whitespace
- escape quotes in values
> [dcmdump] clean strings

- core/src/value/primitive.rs
> [core] Trim padding in more primitive value conversions

- parent/Cargo.toml
- parent/src/lib.rs
- `ul` Cargo feature, enabled by default
> Include dicom-ul in parent crate

- core/src/value/deserialize.rs
Hello Eduardo,
I am trying to work on parsing of date, time and date_time ranges for your library. As I'm playing with the code, I found improvements could be made:
parse_date now can parse a date without MM od DD and still return the rest of the byte stream for UTC offset parsing
(which is DICOM expected behavior for DateTime parsing)
parse_date will not parse a year shorter than 4 bytes
parse_time_impl, when invoked with the "for_datetime" flag, was mistaking a UTC offset for a time fraction (.FFFFFF)
Added some tests as well.
Hope it makes sense and thanks for considering.
> date and time parsing improvements

- dcmdump/src/main.rs
Trim null characters of all UIDs, even the ones in the file meta group
> [dcmdump] clean all strings properly

- scpproxy/src/main.rs
- ul/src/association/client.rs
- ul/src/association/pdata.rs
- ul/src/association/server.rs
- ul/src/pdu/mod.rs
- ul/src/pdu/reader.rs
- ul/src/pdu/writer.rs
- ul/tests/pdu.rs
Hi again @Enet4 another one :-)
Tested with both `dicom-storescu` and `pynetdicom storescu`as clients, and `Orthanc` as a server.
Regards
> [scpproxy] pynetdicom <-> scpproxy <-> Orthanc interop

- parser/src/dataset/write.rs
- parser/src/stateful/encode.rs
- add `StatefulEncode::encode_primitive_element`
- when encoding primitive values, check the real length before writing the header
- deprecate `StatefulEncoder::encode_primitive`
- recommend the other one
> [parser] Don't trust the length in the header for writing

- core/src/header.rs
- core/src/value/deserialize.rs
- core/src/value/mod.rs
- core/src/value/partial.rs
- core/src/value/primitive.rs
- core/src/value/serialize.rs
- encoding/src/encode/basic.rs
- parser/src/stateful/decode.rs
Hi @Enet4,
I changed the PrimitiveValues internals as suggested.
Please be so nice and resolve the problem of the commit being behind the master.
I'm afraid I would mess it up.
Thank you
> Remove chrono

- core/src/header.rs
- core/src/value/mod.rs
- core/src/value/primitive.rs
- object/src/mem.rs
- object/tests/integration_test.rs
- parser/src/dataset/mod.rs
- parser/src/stateful/decode.rs
> strip trailing whitespace when displaying text

- dump/src/main.rs
> [dump] Enable dumping more than one file

- storescu/Cargo.toml
- storescu/src/main.rs
> [storescu] Enable sending more than one file

- storescu/src/main.rs
- ul/src/association/client.rs
- ul/tests/association.rs
> Update to presentation context handling

- object/src/mem.rs
- pixeldata/src/attribute.rs
Added some helper methods for working with DICOM objects where it is expected that some attributes might be missing.
> [object] Add `element_opt` and `element_by_name_opt`

- object/src/mem.rs
- parser/src/dataset/lazy_read.rs
- parser/src/dataset/read.rs
- remove unused fields and dictionary reference
- tweak constructor function names
- [object] adjust use of parser
- derive Default impl of DataSetReaderOptions
> [parser] Clean up dataset readers

- object/src/meta.rs
- accumulate all bytes read instead of decrementing a counter
- prevents subtraction overflow by external DICOM input
- change vec allocations by length
- prevents panicking from OOM caused by malformed DICOM data
- consistently consume value of unexpected or unsupported elements in meta group
Issues identified with the fuzz tests proposed in #258.
> [object] Improve file meta information reading routine

- pixeldata/Cargo.toml
- dicom-test-files 0.2.1
- rstest 0.15
> [pixeldata] Update dev dependencies

- dictionary-builder/Cargo.toml
- dictionary-builder/src/main.rs
> [dictionary-builder] Update dependencies

- echoscu/src/main.rs
- storescu/src/main.rs
- check status code, report them in hexadecimal
- [echoscu] also fix the Message ID check
> Improve response handling in SCU implementations

- storescu/Cargo.toml
- storescu/src/main.rs
- Require at least on file in input instead of reporting "No supported files to transfer".
- Apply minor tool improvements to output in progress bar and in verbose mode.
> [storescu] Improve information and feedback provided by CLI

- object/src/lib.rs
- object/src/meta.rs
- ul/src/lib.rs
> [ul|object] update implementation UID and version name

- core/src/header.rs
- impl `FromStr` for `Tag`
- supports with or without parentheses, fixed length, case insensitive
> [core] Add tag parsing implementation

- object/src/meta.rs
> [object] Add getter methods to FileMetaTable

- core/src/header.rs
> [core] Fix swapped variant documentation

- ul/src/address.rs
- impl `Eq` and `Hash` for `FullAeAddr` and `AeAddr`
- use char for single character pattern matching
> [ul] minor improvements to *AeAddr types

- .github/workflows/rust.yml
Move away from unmaintained actions-rs actions and into [setup-rust-toolchain](https://github.com/actions-rust-lang/setup-rust-toolchain).
> [CI] Update actions

- encoding/Cargo.toml
- fromimage/Cargo.toml
- fromimage/src/main.rs
- pixeldata/Cargo.toml
- [fromimage] [pixeldata] Update `image` to 0.24.5, which already uses `jpeg-decoder` 0.3 underneath
- [encoding] update `jpeg-decoder` to 0.3
> Update image and jpeg decoder

- dictionary-builder/src/main.rs
- parser/src/stateful/encode.rs
- storescp/src/main.rs
- storescu/src/main.rs
- ul/src/association/pdata.rs
- ul/src/pdu/writer.rs
- [dictionary-builder] Clippy fix
- [parser] Clippy fix
- [storescp] Clippy fix
- [storescu] Clippy fix
- [ul] Clippy fix
> Clippy lint fix (2022-12)

- dictionary-builder/Cargo.toml
- dictionary-builder/src/main.rs
- dump/Cargo.toml
- dump/src/main.rs
- echoscu/Cargo.toml
- echoscu/src/main.rs
- findscu/Cargo.toml
- findscu/src/main.rs
- fromimage/Cargo.toml
- fromimage/src/main.rs
- scpproxy/Cargo.toml
- scpproxy/src/main.rs
- storescp/Cargo.toml
- storescp/src/main.rs
- storescu/Cargo.toml
- storescu/src/main.rs
- toimage/Cargo.toml
- toimage/src/main.rs
Updates all crates to clap v4.
> Update all CLI tools to Clap v4

- dictionary-std/src/tags.rs
Breaking change due to renamed and removed variables
> [dictionary-std] Update tag dictionary from DCMTK

- pixeldata/src/lut.rs
This PR changes the behavior of `Lut::get` to discard any bits in the input which go beyond the LUT's allocated capacity (via `bits_stored`), thus making it no longer panic and seamlessly enabling `pixeldata` to convert 9-bit to 15-bit images filling in the highest bits of pixel data sample values.
- add `Lut` field `sample_mask`
- prevents excluded high bits from being considered in the translation
- remove `Lut` field `signed`, which is no longer necessary because masking is always applied
- change `Lut::get` so that it no longer panics
- improve `Lut` documentation
Resolves #346.
> Change LUT to discard high bits of pixel data sample inputs 

- Cargo.lock
- object/fuzz/Cargo.lock
- pixeldata/fuzz/Cargo.lock
- ul/fuzz/Cargo.lock
> Update cargo locks

- core/src/value/mod.rs
- remove outdated extraneous content
- fix typo
> [core] Fix documentation in value module

- Cargo.lock
- echoscu/Cargo.toml
- echoscu/src/main.rs
- Use tracing for verbose logging
- Use dicom_dump to print response on verbose
- Clean up code a bit
> [echoscu] Enhance verbose output

- object/src/lib.rs
- object/src/mem.rs
- Add `InMemDicomObject::update_value`
- Add `InMemDicomObject::put_str`
- Improve documentation in `dicom_object` overall
> Extend object updating API and extend documentation

- findscu/README.md
- findscu/src/query.rs
findscu can now describe nested data elements in the C-FIND queries!
> Use attribute ops API for C-FIND query construction

- object/src/lib.rs
- object/src/mem.rs
Uses attribute selection for plain retrieval at an arbitrary depth.
> [object] Add method value_at

- Cargo.lock
- core/Cargo.toml
- dump/Cargo.toml
- object/Cargo.toml
- object/fuzz/Cargo.lock
- pixeldata/fuzz/Cargo.lock
- ul/fuzz/Cargo.lock
- [core/object] update to v0.11
- [dump] remove unused dependency
- update cargo locks
> Update itertools (v0.11)

- Cargo.lock
- fromimage/Cargo.toml
- pixeldata/Cargo.toml
> Add "openexr" image feature by default

- object/src/meta.rs
This fixes a DICOM data writing inconsistency when changing the transfer syntax and subsequently writing to a file without updating the file meta group length.
> Update group length when setting transfer syntax

- README.md
- transfer-syntax-registry/src/lib.rs
- [ts-registry] tweak root level documentation
- Tweak readme
> Documentation tweaks

- Cargo.lock
- core/Cargo.toml
- object/Cargo.toml
- object/fuzz/Cargo.lock
- pixeldata/fuzz/Cargo.lock
- ul/fuzz/Cargo.lock
- Update itertools to 0.12
- Cargo update
> Update dependencies (2023-11 general maintenance)

- core/src/header.rs
- core/src/ops.rs
- encoding/src/transfer_syntax/mod.rs
- object/src/lib.rs
- object/src/mem.rs
- object/src/meta.rs
- pixeldata/src/attribute.rs
- pixeldata/src/lib.rs
- transfer-syntax-registry/src/lib.rs
- ul/src/association/client.rs
- ul/src/association/mod.rs
- ul/src/association/server.rs
- ul/src/lib.rs
Clean up docs and resolve Clippy lint warnings.
> Maintenance lint fixes

- dictionary-std/src/tags.rs
- dictionary-std/src/uids.rs
Update data element (tags) and unique identifier (uids) dictionaries.
> [dictionary-std] Update dictionary entries

- findscu/src/main.rs
Fixes https://github.com/Enet4/dicom-rs/discussions/527
Fixes https://github.com/Enet4/dicom-rs/issues/522
After several attempts, it turned out that Harmony sends all the data at once, unlike orthanc and https://dicomserver.co.uk/
Now downloading patient data from Harmony works fine
> Fix Harmowy worklist server

- core/src/value/deserialize.rs
- core/src/value/range.rs
- encoding/src/transfer_syntax/mod.rs
- json/src/ser/mod.rs
- object/src/mem.rs
- object/src/meta.rs
- parser/src/stateful/encode.rs
- pixeldata/src/lib.rs
- pixeldata/src/lut.rs
- toimage/src/main.rs
- ul/src/lib.rs
- [core] Fix minor doc-comment formatting
- [encoding] clippy lint fix
- [parser] Clippy lint fix
- [ul] Fix minor doc-comment formatting
- [object] Clippy lint fix
- [pixeldata] Clippy lint fix
- [json] Clippy lint fix
> Lint (2024-07)

- findscu/README.md
- findscu/src/main.rs
Adds support for passing the query lines from a text file.
> [findscu] Add query_file argument

- storescu/src/main.rs
Hi,
As addressed in #473 , I have slightly adapted the [`check_presentation_context()`](https://github.com/Enet4/dicom-rs/blob/master/storescu/src/main.rs#L563) function to return early if there is an exact match between the file's TS and the TS from the presentation contexts slice that is passed to the function. Otherwise, the previous logic applies. When testing, the selected_ts is consistently the same as the file's TS.
Is it the expected behavior for storescu ?
Additionally, you commented:
> (...)
> The other criterion currently written is to transcode and accept Explicit VR Little Endian otherwise (only when `--never-transcode` is not enabled).
> (...)
_Originally posted by @Enet4 in https://github.com/Enet4/dicom-rs/issues/473#issuecomment-2117643092_
I am uncertain how to address …
> [storescu] prefer file's transfer syntax

- json/src/ser/mod.rs
> Raise a recoverable error when trying to serialize encapsulated pixel data

- object/src/meta.rs
Fixes a mistake in `FileMetaTable` group length calculation, by accounting for a possible padding in optional attributes.
> Adjust file meta information group length calculation

- pixeldata/src/lib.rs
Hi,
this PR adds a very simple interleave function to handle planar pixel configurations when decoding pixel data. I only have planar RGB8 files to test, but I don't see why 16-bit files would behave very differently...
The interleave implementation is very simple, but seems to yield decent performance (30ms to interleave a 12MP image on my 10 year old laptop). I experimented with a more "imperative" version with for loops which ended up being *slower* (probably because of bound checks), and a simple SSE implementation based on mm_shuffle_epi8 wasn't significantly faster either.
> [pixeldata] Add support for PixelFirst planar configuration (#129)

- dictionary-std/src/tags.rs
Include breaking changes caused by data element renaming
> [dictionary-std] Update DICOM tag dictionary again

- ul/src/association/client.rs
- ul/tests/association_promiscuous.rs
> Return in ClientAssociation also User Variables

- storescp/src/store_async.rs
- storescp/src/store_sync.rs
> fix(scp): use max_pdu_length method to set the value

- dump/src/main.rs
Adds support for a stop tag in the CLI tool `dicom-dump`
> [dump] Add CLI option read_until

- object/src/mem.rs
- parser/src/dataset/write.rs
This fixes a regression from #645 (CC @jmlaka).
Per [PS3.5 A.4](https://dicom.nema.org/medical/dicom/current/output/chtml/part05/sect_A.4.html), the length of pixel data fragment items is always explicitly defined, so they should not be affected by the explicit length sequence strategy.
- track whether `DataSetWriter` printing a pixel data fragment sequence and keep lengths if so
- update test `dataset::write::write_encapsulated_pixeldata` accordingly
- Tweak documentation on ExplicitLengthSqItemStrategy
- [object] add test for writing a data set with encapsulated pixel data
> [parser] Do not clear length of pixel data fragment item starts
